"""
Delivers the daily LinkedIn content package via Gmail and uploads to Google Drive.
- Creates a dated folder in Google Drive
- Uploads slide_1.png, slide_2.png, slide_3.png
- Sends an email to becbennett90@gmail.com with post copy + Drive link + slides attached
Usage: python3 tools/deliver_content.py
"""

import os
import json
import base64
import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from dotenv import load_dotenv
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

load_dotenv()

SCOPES = [
    "https://www.googleapis.com/auth/drive.file",
    "https://mail.google.com/",
]

TOKEN_PATH = "token.json"
RECIPIENT = "becbennett90@gmail.com"
CONTENT_FILE = ".tmp/linkedin_content.json"
SLIDES = [".tmp/slide_1.png", ".tmp/slide_2.png", ".tmp/slide_3.png"]


def get_services():
    creds = Credentials.from_authorized_user_file(TOKEN_PATH, SCOPES)
    drive = build("drive", "v3", credentials=creds)
    gmail = build("gmail", "v1", credentials=creds)
    return drive, gmail


def create_drive_folder(drive, date_str):
    parent_id = os.getenv("GOOGLE_DRIVE_OUTPUT_FOLDER_ID") or None
    meta = {
        "name": f"LinkedIn Content {date_str}",
        "mimeType": "application/vnd.google-apps.folder",
    }
    if parent_id:
        meta["parents"] = [parent_id]
    folder = drive.files().create(body=meta, fields="id, webViewLink").execute()
    return folder["id"], folder["webViewLink"]


def upload_slides(drive, folder_id):
    links = []
    for slide_path in SLIDES:
        if not os.path.exists(slide_path):
            continue
        name = os.path.basename(slide_path)
        media = MediaFileUpload(slide_path, mimetype="image/png")
        f = drive.files().create(
            body={"name": name, "parents": [folder_id]},
            media_body=media,
            fields="id, webViewLink"
        ).execute()
        links.append(f["webViewLink"])
    return links


def send_email(gmail, content, folder_link, date_str):
    post_text = content["post"]
    topic = content["chosen_topic"]
    source = content["source"]
    slides_data = content["slides"]

    html_body = f"""
<h2>Your LinkedIn Content for {date_str} 🚀</h2>

<h3>Today's Topic</h3>
<p><strong>{topic}</strong><br>Source: {source}</p>

<hr>

<h3>LinkedIn Post Copy</h3>
<pre style="font-family:sans-serif; white-space:pre-wrap; background:#f4f4f4; padding:16px; border-radius:8px;">{post_text}</pre>

<hr>

<h3>Carousel Slide Copy</h3>
<p><strong>Slide 1 — Hook</strong><br>
Headline: {slides_data['slide_1']['headline']}<br>
Subheading: {slides_data['slide_1']['subheading']}</p>

<p><strong>Slide 2 — Insight</strong><br>
Headline: {slides_data['slide_2']['headline']}<br>
• {slides_data['slide_2']['bullets'][0]}<br>
• {slides_data['slide_2']['bullets'][1]}<br>
• {slides_data['slide_2']['bullets'][2]}</p>

<p><strong>Slide 3 — CTA</strong><br>
{slides_data['slide_3']['statement']}<br>
{slides_data['slide_3']['cta']}</p>

<hr>
<p>📁 <a href="{folder_link}">Open slides in Google Drive</a></p>
<p style="color:#888; font-size:12px;">Generated by Growth Lab Co. Content Workflow</p>
"""

    msg = MIMEMultipart("mixed")
    msg["To"] = RECIPIENT
    msg["From"] = RECIPIENT
    msg["Subject"] = f"🎯 Your LinkedIn Content is Ready — {date_str}"
    msg.attach(MIMEText(html_body, "html"))

    for slide_path in SLIDES:
        if not os.path.exists(slide_path):
            continue
        with open(slide_path, "rb") as f:
            part = MIMEBase("image", "png")
            part.set_payload(f.read())
            encoders.encode_base64(part)
            part.add_header("Content-Disposition", f"attachment; filename={os.path.basename(slide_path)}")
            msg.attach(part)

    raw = base64.urlsafe_b64encode(msg.as_bytes()).decode()
    gmail.users().messages().send(userId="me", body={"raw": raw}).execute()
    print(f"✓ Email sent to {RECIPIENT}")


if __name__ == "__main__":
    date_str = datetime.date.today().strftime("%Y-%m-%d")

    with open(CONTENT_FILE) as f:
        content = json.load(f)

    drive, gmail = get_services()

    print("Creating Drive folder...")
    folder_id, folder_link = create_drive_folder(drive, date_str)
    print(f"✓ Drive folder: {folder_link}")

    print("Uploading slides...")
    upload_slides(drive, folder_id)

    print("Sending email...")
    send_email(gmail, content, folder_link, date_str)

    print("✓ Delivery complete.")
